config/routes.rb
Rails.application.routes.draw do
  get "log_games/my_history"
  get "log_games/leadboard"
  resources :log_games
  devise_for :users
  root to: "home#index"
  get '/history', to: 'home#history'
  get '/log',     to: 'home#log'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user
      can [:index, :new, :create, :destroy, :show], LogGame, id: user.id
      can [:leadboard, :my_history], LogGame
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/log_game.rb
class LogGame < ActiveRecord::Base
  belongs_to :user
  belongs_to :opponent, foreign_key: :opponent_id, class_name: 'User'
  validates :date_played, :user_id, :your_score, :opponent_id, :opponent_score, presence: true
  validate :get_correct_score_margin, if:  (:your_score? and :opponent_score?)
  
  def get_correct_score_margin
    if (your_score - opponent_score)*(-1) != 2
      errors[:base] << 'Score difference must be not more or less than two points.'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable
  has_many :log_games, dependent: :destroy
  has_many :log_games, foreign_key: :opponent_id, dependent: :destroy
  validates :name, format: { with: /^[a-zA-ZñÑáéíóúÁÉÍÓÚ .,]+$/, multiline: true }, length: { within: 1..60 }
  #Users email and password can be validated in devise initializer
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def history
  end

  def log
  end
end

app/controllers/log_games_controller.rb
class LogGamesController < ApplicationController
  before_action :set_log_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource except: [:create]
  
  def my_history
    @log_games = LogGame.where(user_id: current_user.id).order('log_game_won_by_you DESC').uniq
  end
  
  def leadboard

  end

  # GET /log_games
  def index
    @index_controller_name = 'log_games'
    @log_games = LogGame.where(user_id: current_user.id)
  end

  # GET /log_games/1
  def show
  end

  # GET /log_games/new
  def new
    @log_game = LogGame.new
  end

  # GET /log_games/1/edit
  def edit
  end

  # POST /log_games
  def create
    @log_game = LogGame.new(log_game_params)

    if @log_game.save
      if @log_game.your_score > @log_game.opponent_score
        @log_game_won_by_you = true
      end
      redirect_to @log_game, notice: 'Log game was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /log_games/1
  def update
    if @log_game.update(log_game_params)
      redirect_to @log_game, notice: 'Log game was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /log_games/1
  def destroy
    @log_game.destroy
    redirect_to log_games_url, notice: 'Log game was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_log_game
    @log_game = LogGame.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def log_game_params
    params.require(:log_game).permit(:date_played, :user_id, :opponent_id, :your_score, :opponent_score, :log_game_won_by_you)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
    flash_collection = []
    if flash[:notice]
      flash_collection << flash_type('info', flash[:notice])
    elsif flash[:error]
      flash_collection << flash_type('danger', flash[:error])
    elsif flash[:alert]
      flash_collection << flash_type('warning', flash[:alert])
    elsif flash[:success]
      flash_collection << flash_type('success', flash[:success])
    end
    return flash_collection.join.html_safe
  end
  
  def flash_type(type, message)
    button_properties = {
      :type => 'button', 
      :class => 'btn close',
      :'data-dismiss' => 'alert', 
      :'aria-label' => 'Close'
    }
    content_tag(:div, :class => "alert alert-#{type} alert-dismissible") do
      concat(message)
      concat(content_tag(:button, button_properties) do
          content_tag(:span, :'aria-hidden' => 'true') do
            concat('&times;'.html_safe)
          end
        end)
    end    
  end
  
  def show_action_links?
    actions = [
      'new', 
      'create', 
      'edit', 
      'update', 
      'index', 
      'show', 
      'destroy']
    (actions.include?(action_name) and is_model?(get_controller_name)) ? true : false
  end
  
  def get_controller_name
    devise_controllers = [
      'registrations', 
      'sessions', 
      'confirmations', 
      'omniauth_callbacks', 
      'passwords', 
      'unlocks'
    ]
    return devise_controllers.include?(controller_name) ? 'users' : controller_name
  end 
  
  def is_model?(model)
    if File.exist?("app/models/#{to_model_file_name(model)}.rb")
      return true
    else
      return false
    end
  end
  
  def to_model(model)
    name = eval("#{to_model_name(model)}")
    return name
  rescue
    'Error on to_model: ' + model.to_s
  end
  
  def to_model_name(model)
    name = model.to_s.gsub('_id', '').singularize.camelize
    return name
  rescue
    'Error on to_model_name: ' + model.to_s
  end
  
  def to_model_file_name(model)
    name = model.to_s.gsub('_id', '').tableize.singularize
    return name
  rescue
    'Error on to_model_file_name: ' + model.to_s
  end
  
  def to_controller_name(model)
    name = model.to_s.gsub('_id', '').tableize
    return name
  rescue
    'Error on to_controller_name: ' + model.to_s
  end
  
  def have_any_index_action?(model)
    if can? :show, to_model(model) or can? :edit, to_model(model) or can? :destroy, to_model(model)
      return true
    else
      return false
    end
  end
  
  def has_action?(controller, action)
    controller = controller.nil? ? controller_name : to_controller_name(controller)
    "#{controller}_controller".camelize.constantize.new.respond_to?(action)
  rescue
    false
  end
  
  
end

app/helpers/log_games_helper.rb
module LogGamesHelper
end

app/views/home/history.html.haml
%h1.page-header History
.alert.alert-warning{:role => "alert"} This is a sample page. Replace link in the header with your own.
= image_tag('history.png')

app/views/home/index.html.haml
%h1.page-header Leaderboard
.alert.alert-warning{:role => "alert"} This is a sample page.
= image_tag('leaderboard.png')

app/views/home/log.html.haml
%h1.page-header Log Game
.alert.alert-warning{:role => "alert"} This is a sample page. Replace link in the header with your own.
= image_tag('log_game.png')

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Pingpong
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      = link_to 'Log Game', new_log_game_path, class: 'btn btn-success navbar-btn'
      %ul.nav.navbar-nav
        - if user_signed_in?
          %li= link_to 'Leadboard', log_games_leadboard_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to "Games History", log_games_path
          %li
            = link_to "My History Games", log_games_my_history_path
          %li= link_to 'Logout', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Login', new_user_session_path
          %li= link_to 'Sign up', new_user_registration_path
    / /.navbar-collapse

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Pingpong Leaderboard
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous"
    = javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      %h2= controller_name.titlecase
      .panel-group
        .panel.panel-primary
          .panel-heading="#{action_name} new #{controller_name}".titlecase
          = flash_message
          .panel-body
            = yield
            = render 'partials/admin/action_links' if show_action_links?

app/views/log_games/_form.html.haml
= simple_form_for(@log_game) do |f|
  = f.error_notification

  .form-inputs
    = f.input :date_played, as: :datetime, order: [:day, :month, :year]
    = f.association :user
    = f.association :opponent
    = f.input :your_score, hint: 'Score difference must be not more or less than two points.'
    = f.input :opponent_score, hint: 'Score difference must be not more or less than two points.'

  .form-actions
    = f.button :submit

app/views/log_games/edit.html.haml
= render 'form'

app/views/log_games/index.html.haml
%table.table.table-striped.table-bordered
  %thead
    %tr
      %th Date played
      %th User
      %th Opponent
      %th Your score
      %th Opponent score
      %th Acction Links

  %tbody
    - @log_games.each do |log_game|
      - @model = log_game
      %tr
        %td= log_game.date_played
        %td= log_game.user.name
        %td= log_game.opponent.name
        %td= log_game.your_score
        %td= log_game.opponent_score
        - if have_any_index_action?(controller_name)
          %td= render 'partials/admin/index_links'

app/views/log_games/leadboard.html.haml
%table.table.table-striped.table-bordered
  %thead
    %tr
      %th Won games
      %th Date played
      %th User
      %th Opponent
      %th Your score
      %th Opponent score

  %tbody
    - @log_games.each do |log_game|
      %tr
        %th= LogGame.where("user_id = #{log_game.user_id} and log_game_won_by_you = true").count
        %td= log_game.date_played
        %td= log_game.user.name
        %td= log_game.opponent.name
        %td= log_game.your_score
        %td= log_game.opponent_score

app/views/log_games/my_history.haml
%table.table.table-striped.table-bordered
  %thead
    %tr
      %th Won?
      %th Date played
      %th User
      %th Opponent
      %th Your score
      %th Opponent score

  %tbody
    - @log_games.each do |log_game|
      %tr
        %td= log_game.log_game_won_by_you ? 'YES' : 'NO'
        %td= log_game.date_played
        %td= log_game.user.name
        %td= log_game.opponent.name
        %td= log_game.your_score
        %td= log_game.opponent_score

app/views/log_games/new.html.haml
= render 'form'

app/views/log_games/show.html.haml
%p
  %b Date played:
  = @log_game.date_played
%p
  %b User:
  = @log_game.user.name
%p
  %b Opponent:
  = @log_game.opponent.name
%p
  %b Your score:
  = @log_game.your_score
%p
  %b Opponent score:
  = @log_game.opponent_score

app/views/partials/admin/_action_links.haml
.action_links
  - if action_name == 'new' or action_name == 'create'
    - if can? :index, to_model(get_controller_name)
      = link_to eval("#{get_controller_name}_path"), class: 'btn btn-md btn-primary' do
        %i.fa.fa-arrow-circle-left
        Back
  - elsif action_name == 'index'
    - if can? :new, to_model(get_controller_name)
      = link_to eval("new_#{get_controller_name.singularize}_path"), class: 'btn btn-md btn-success' do
        %i.fa.fa-plus
        New
  - elsif action_name == 'edit' or action_name == 'update' or action_name == 'show'
    - if can? :index, to_model(get_controller_name)
      = link_to eval("#{get_controller_name}_path"), class: 'btn btn-md btn-primary' do
        %i.fa.fa-arrow-circle-left
        Back
    - if can? :new, to_model(get_controller_name)
      = link_to eval("new_#{get_controller_name.singularize}_path"), class: 'btn btn-md btn-success' do
        %i.fa.fa-plus
        New
    - if get_controller_name == 'users' and @user.id != current_user.id
      - if can? :edit, User
        = link_to edit_admin_user_path(@user), class: 'btn btn-md btn-warning' do
          %i.fa.fa-pencil
          Edit
    - else
      - if can? :edit, to_model(get_controller_name) and action_name != 'edit' and action_name != 'update'
        = link_to eval("edit_#{get_controller_name.singularize}_path(@#{get_controller_name.singularize})"), class: 'btn btn-md btn-warning' do
          %i.fa.fa-pencil
          Edit
    - if get_controller_name == 'users' and @user.id != current_user.id
      - if can? :destory, to_model(get_controller_name) and @user.id != current_user.id
        = link_to eval("@#{get_controller_name.singularize}"), method: :delete , class: 'btn btn-md btn-danger' do
          %i.fa.fa-trash
          Edit
    - elsif get_controller_name != 'users'
      - if can? :destory, to_model(get_controller_name)
        = link_to eval("@#{get_controller_name.singularize}"), method: :delete , class: 'btn btn-md btn-danger' do
          %i.fa.fa-trash
          Destroy

app/views/partials/admin/_index_links.haml
.btn-group
  %button.btn.btn-white.dropdown-toggle{'data-toggle':'dropdown', 'aria-haspopup':'true', 'aria-expanded':'true'}
    %i.fa.fa-cog
    %span.caret
  %ul.dropdown-menu
    - if controller_name == 'contacts' and can? :edit, Contact
      %li
        = link_to contacts_mark_as_saw_path(id: @model.id), title: t('actions.mark_as_saw',  model: t("activerecord.models.#{@index_controller_name.singularize}")) do
          %i.fa.fa-check
          = t('actions.mark_as_saw',  model: t("activerecord.models.#{@index_controller_name.singularize}"))
      %li.divider
    - if can? :show, eval(@index_controller_name.camelize.singularize) and has_action?(nil, 'show')
      %li
        = link_to @model, title: t('actions.show',  model: t("activerecord.models.#{@index_controller_name.singularize}")) do
          %i.fa.fa-eye-slash
          = t('actions.show',  model: t("activerecord.models.#{@index_controller_name.singularize}"))
    - if can? :edit, eval(@index_controller_name.camelize.singularize) and has_action?(nil, 'edit')
      %li.divider
      - if @index_controller_name == "users" and @model.id != current_user.id
        %li
          = link_to edit_admin_user_path(@model), title: t('actions.edit',  model: t("activerecord.models.#{@index_controller_name.singularize}")) do
            %i.fa.fa-pencil
            = t('actions.edit',  model: t("activerecord.models.#{@index_controller_name.singularize}"))
      - else
        %li
          = link_to eval("edit_#{@index_controller_name.singularize}_path(@model)"), title: t('actions.edit',  model: t("activerecord.models.#{@index_controller_name.singularize}")) do
            %i.fa.fa-pencil
            = t('actions.edit',  model: t("activerecord.models.#{@index_controller_name.singularize}"))
    - if can? :destroy, eval(@index_controller_name.camelize.singularize) and has_action?(nil, 'destroy')
      - if @index_controller_name == "users"
        - unless @model.id == current_user.id
          %li.divider
          %li
            = link_to @model, method: :delete, data: { confirm: t('actions.are_you_sure?', model: t("activerecord.models.#{@index_controller_name.singularize}")) }, title: t('actions.destroy',  model: t("activerecord.models.#{@index_controller_name.singularize}")) do
              %i.fa.fa-trash-o
              = t('actions.destroy',  model: t("activerecord.models.#{@index_controller_name.singularize}"))
      - else
        %li.divider
        %li
          = link_to @model, method: :delete, data: { confirm: t('actions.are_you_sure?', model: t("activerecord.models.#{@index_controller_name.singularize}")) }, title: t('actions.destroy',  model: t("activerecord.models.#{@index_controller_name.singularize}")) do
            %i.fa.fa-trash-o
            = t('actions.destroy',  model: t("activerecord.models.#{@index_controller_name.singularize}"))